version: '2'

catalog:
  name: "CNETS Storage"
  version: "v1.0.0"
  description: "File Storage & Share powered by Fujitsu CNETS Team"
  uuid: cnets-storage-0
  minimum_rancher_version: v0.51.0
  questions:

services:
  mariadb:
    scale: 1
    start_on_create: true
  nextcloud:
    scale: 1
    start_on_create: true
  mariadb-data:
    scale: 1
    start_on_create: true
  nextcloud-data:
    scale: 1
    start_on_create: true
  nextcloud-lb:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      default_cert: cnets-mdiego
      port_rules:
      - priority: 1
        protocol: http
        service: nextcloud
        source_port: 80
        target_port: 80
      - priority: 2
        protocol: https
        service: nextcloud
        source_port: 443
        target_port: 80
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 42
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      reinitializing_timeout: 60000
