---
resources:
- name: k5-rancher
  type: git
  source:
    uri: https://github.com/madhosoi/k5-rancher.git

jobs:
- name: job-hello-world
  public: true
  plan:
  - get: k5-rancher
  - task: hello-world
    file: k5-rancher/Concourse/pipelines/helloworld-task.yml
