---

resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest

resources:
- name: k5-rancher
  type: git
  source:
    uri: https://github.com/madhosoi/k5-rancher.git

- name: madhosoi-slack
  type: slack-notification
  source:
    url: https://hooks.slack.com/services/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

jobs:
- name: job-hello-world
  public: true
  plan:
  - get: k5-rancher
    trigger: true
  - task: hello-world
    file: k5-rancher/Concourse/pipelines/helloworld-task.yml
  - put: madhosoi-slack
    params:
      text: <!channel> Hi everybody!
      channel: "#general"
      username: madhosoibot
      icon_url: http://cl.ly/image/3e1h0H3H2s0P/concourse-logo.png

