version: '2'
services:
  concourse-db:
    scale: 1
    start_on_create: true
  concourse-web:
    scale: 1
    start_on_create: true
  concourse-worker:
    scale: 1
    start_on_create: true
  concourse-lb:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - priority: 1
        protocol: tcp
        service: concourse-web
        source_port: 8081
        target_port: 8080
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 42
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      reinitializing_timeout: 60000
